# Generated by Django 6.0.3 on 2026-03-18 21:40

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Article',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('input_type', models.CharField(choices=[('text', 'Text'), ('url', 'URL'), ('file', 'File')], max_length=10)),
                ('original_url', models.URLField(blank=True, max_length=2048)),
                ('title', models.CharField(blank=True, max_length=500)),
                ('author', models.CharField(blank=True, max_length=255)),
                ('source_name', models.CharField(blank=True, max_length=255)),
                ('publication_date', models.DateField(blank=True, null=True)),
                ('content', models.TextField()),
                ('uploaded_file', models.FileField(blank=True, null=True, upload_to='article_uploads/')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='articles', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'articles',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='AnalysisResult',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('processing', 'Processing'), ('completed', 'Completed'), ('failed', 'Failed')], default='pending', max_length=20)),
                ('current_stage', models.IntegerField(default=0)),
                ('current_stage_name', models.CharField(blank=True, max_length=50)),
                ('naive_bayes_score', models.FloatField(blank=True, null=True)),
                ('lstm_score', models.FloatField(blank=True, null=True)),
                ('distilbert_score', models.FloatField(blank=True, null=True)),
                ('ensemble_score', models.FloatField(blank=True, null=True)),
                ('credibility_score', models.FloatField(blank=True, null=True)),
                ('classification', models.CharField(blank=True, choices=[('FAKE', 'Fake'), ('REAL', 'Real'), ('UNCERTAIN', 'Uncertain')], max_length=20)),
                ('confidence', models.FloatField(blank=True, null=True)),
                ('sentiment_score', models.FloatField(blank=True, null=True)),
                ('emotional_tone', models.CharField(blank=True, max_length=50)),
                ('sensationalism_score', models.FloatField(blank=True, null=True)),
                ('headline_body_consistency', models.FloatField(blank=True, null=True)),
                ('top_keywords', models.JSONField(blank=True, default=list)),
                ('flagging_reasons', models.JSONField(blank=True, default=list)),
                ('feature_vector', models.JSONField(blank=True, default=dict)),
                ('is_flagged_for_review', models.BooleanField(default=False)),
                ('celery_task_id', models.CharField(blank=True, max_length=255)),
                ('error_message', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('completed_at', models.DateTimeField(blank=True, null=True)),
                ('flagged_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='flagged_results', to=settings.AUTH_USER_MODEL)),
                ('article', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='result', to='analysis.article')),
            ],
            options={
                'db_table': 'analysis_results',
                'ordering': ['-created_at'],
            },
        ),
    ]
